artifact_uri: file:///C:/Users/ulas/Desktop/Telco-Customer-Churn-ML/mlruns/974953631381130799/860e768b3baf41e5832ceb20e9b330ba/artifacts
end_time: 1771272925405
entry_point_name: ''
experiment_id: '974953631381130799'
lifecycle_stage: active
run_id: 860e768b3baf41e5832ceb20e9b330ba
run_name: valuable-perch-898
source_name: ''
source_type: 4
source_version: ''
start_time: 1771272920337
status: 3
tags: []
user_id: ulas
