channels:
- conda-forge
dependencies:
- python=3.11.14
- pip
- pip:
  - mlflow==3.9.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.16.1
  - xgboost==3.0.3
name: mlflow-env
